#ifndef _OPERATOR_H_
#define _OPERATOR_H_
enum operator {E_PLUS, E_MINUS, E_MULT, E_DIV,
	E_IF, E_SUPERIOR, E_INFERIOR,
	E_EQUAL, E_DIFFERENT, E_SUPEQUAL,
	E_INFEQUAL, E_ASSIGN, E_OR, E_NO, E_AND,E_RETURN, E_PRINTI, E_PRINTF};

#endif
